ROLE_DEFINITION = [:SUPER_ADMIN, :ADMIN, :DEV, :FIN, :PLM, :SALES, :MATERIAL_CONTROLLER, :POST_SALES, :OTHER]
COMPONENT_CATEGORY_DEFINITION = [:CATEGORY_LEVEL1, :CATEGORY_LEVEL2, :CATEGORY_LEVEL3, :CATEGORY_LEVEL4]
CATEGORY_MAP = {:CATEGORY_LEVEL1 => "level1", :CATEGORY_LEVEL2 => "level2", :CATEGORY_LEVEL3 => "level3", :CATEGORY_LEVEL4 => "level4"}