class AddCategory2ndData < ActiveRecord::Migration
  def up
  	Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '01', :category_name => I18n.t('Resistance', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_01', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '02', :category_name => I18n.t('Capacitance', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_02', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '03', :category_name => I18n.t('Inductance', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_03', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '04', :category_name => I18n.t('Power Class Devices', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_04', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '05', :category_name => I18n.t('Baseband IC', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_05', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '06', :category_name => I18n.t('RF TxRv IC', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_06', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '07', :category_name => I18n.t('RF PA and Switches', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_07', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '08', :category_name => I18n.t('Filter', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_08', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '09', :category_name => I18n.t('Crystal', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_09', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '10', :category_name => I18n.t('Transistor', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_10', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '11', :category_name => I18n.t('Memory', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_11', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '12', :category_name => I18n.t('Connector', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_12', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '13', :category_name => I18n.t('Audio Devices', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_13', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '14', :category_name => I18n.t('Other ICs', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_14', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '15', :category_name => I18n.t('Non RF Switches', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_15', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '16', :category_name => I18n.t('Fuse', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_16', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '17', :category_name => I18n.t('ESD & EMI Filter', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_17', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '18', :category_name => I18n.t('Reserve 1', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_18', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '19', :category_name => I18n.t('Dielectric Antenna', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_19', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '81').first.id, :category_encoding => '20', :category_name => I18n.t('Modules', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_81_20', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
                            
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '82').first.id, :category_encoding => '01', :category_name => I18n.t('PCB', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_82_01', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '82').first.id, :category_encoding => '02', :category_name => I18n.t('Shielding Box', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_82_02', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)
    Category2nd.create!(:category1st_id => Category1st.where(:category_encoding => '82').first.id, :category_encoding => '03', :category_name => I18n.t('Modules', :scope => 'category_2nd_name'), :category_comment => I18n.t('level_2nd_comment_82_03', :scope => 'category_2nd_comment'), :updated_by_email => AdminUser.where(:role => "SUPER_ADMIN").first.email)        
  end

  def down
  end
end
